---
# tasks file for myapp_infra
- name: create app security group
  ec2_group:
    name: "{{ app_name }}"
    description: "{{ app_name }} security group"
    region: "{{ region }}"
    rules: "{{ sec_group_rules }}"
    vpc_id: "{{ vpc_id }}"
  tags: security_groups
  register: app_security_group

- name: create launch config
  ec2_lc:
    name: "{{ app_name }}"
    image_id: "{{ ami }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    security_groups: "{{ app_security_group.group_id }},{{ tower_callback_client_group_id }},{{ tower_client_group_id }}"
    instance_type: "{{ instance_size }}"
    user_data: "{{ user_data }}"
  tags: launch_config
